// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevaliInstruct.Core.Data;

#nullable disable

namespace RevaliInstruct.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RevaliInstruct.Core.Entities.AccessoryAdvice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdviceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HuisartsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("AccessoryAdvices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdviceDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "6 weken",
                            HuisartsId = 3,
                            Name = "Krukken",
                            PatientId = 1,
                            Status = "Actief"
                        },
                        new
                        {
                            Id = 2,
                            AdviceDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = "12 weken",
                            HuisartsId = 3,
                            Name = "Kniebrace",
                            PatientId = 1,
                            Status = "Actief"
                        });
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.ActivityLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDateTime = new DateTime(2025, 1, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            DurationMinutes = 60,
                            PatientId = 1,
                            Status = "Afgerond",
                            Type = "Intake"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDateTime = new DateTime(2025, 1, 31, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            DurationMinutes = 45,
                            PatientId = 1,
                            Status = "Afgerond",
                            Type = "Controle"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDateTime = new DateTime(2025, 4, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            DurationMinutes = 30,
                            PatientId = 1,
                            Status = "Gepland",
                            Type = "Controle"
                        });
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Langzaam knieën buigen tot 90 graden rug recht houden.",
                            Name = "Kniebuiging",
                            VideoUrl = "https://www.youtube.com/watch?v=00g8DINXtIY"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Zittend één been gestrekt",
                            Name = "Hamstring Stretch",
                            VideoUrl = "https://www.youtube.com/shorts/ywgDXzYD6v8"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Op de tenen staan en langzaam zakken.",
                            Name = "Calf Raises",
                            VideoUrl = "https://www.youtube.com/watch?v=eMTy3qylqnE"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Plankpositie rug recht",
                            Name = "Core Stability Plank",
                            VideoUrl = "https://www.youtube.com/watch?v=pvIjsG5Svck"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cirkelbewegingen met de armen.",
                            Name = "Schouder Rotaties",
                            VideoUrl = "https://www.youtube.com/watch?v=oLwTC-lAJws&list=PLurruTwy8-10c7tAfYnJRkFVy_U1O3IZ1"
                        });
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.ExerciseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("PatientId");

                    b.ToTable("ExerciseAssignments");
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.IntakeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("IntakeRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Gescheurde kruisbanden (ACL)",
                            DoctorId = 5,
                            Goals = "Volledig herstel kniefunctie; wondgenezing; pijnmanagement",
                            PatientId = 1,
                            Severity = "Ernstig"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Hernia L5-S1",
                            DoctorId = 6,
                            Goals = "Pijnreductie; mobiliteit; terugkeer naar werk",
                            PatientId = 2,
                            Severity = "Matig"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Schouder impingement",
                            DoctorId = 5,
                            Goals = "Pijnvrij bewegen; krachtopbouw",
                            PatientId = 3,
                            Severity = "Licht tot matig"
                        });
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 3500m,
                            AuthorId = 3,
                            Date = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Consult wondverzorging arm",
                            PatientId = 1,
                            Status = "Nieuw",
                            Type = "Huisarts"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 8000m,
                            AuthorId = 5,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intake revalidatie knie",
                            PatientId = 1,
                            Status = "Nieuw",
                            Type = "Revalidatiearts"
                        });
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.PainEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PainEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Note = "Na de operatie",
                            PatientId = 1,
                            Score = 7,
                            Timestamp = new DateTime(2025, 1, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Note = "Iets minder pijn",
                            PatientId = 1,
                            Score = 6,
                            Timestamp = new DateTime(2025, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Note = "Pijn bij bewegen",
                            PatientId = 1,
                            Score = 5,
                            Timestamp = new DateTime(2025, 1, 12, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssignedDoctorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDoctorUserId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kruisbandstraat 10",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "freddy.v@example.com",
                            FirstName = "Freddy",
                            LastName = "Voetballer",
                            StartDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Therapiestraat 5",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1988, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.k@example.com",
                            FirstName = "Anna",
                            LastName = "Kamer",
                            StartDate = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Oefenlaan 12",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1976, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bas.v@example.com",
                            FirstName = "Bas",
                            LastName = "Verkade",
                            StartDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Herstelweg 3",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(2001, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carla.d@example.com",
                            FirstName = "Carla",
                            LastName = "Dirksen",
                            StartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Revalidatieplein 7",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1965, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dirk.m@example.com",
                            FirstName = "Dirk",
                            LastName = "Meijer",
                            StartDate = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        },
                        new
                        {
                            Id = 6,
                            Address = "Fysioweg 22",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1999, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.p@example.com",
                            FirstName = "Eva",
                            LastName = "Peters",
                            StartDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Address = "Gipsstraat 1",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1970, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "frank.dj@example.com",
                            FirstName = "Frank",
                            LastName = "de Jong",
                            StartDate = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Address = "Rolstoelpad 8",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1985, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "greetje.w@example.com",
                            FirstName = "Greetje",
                            LastName = "Willems",
                            StartDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "Sportlaan 15",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1993, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hans.k@example.com",
                            FirstName = "Hans",
                            LastName = "Kramer",
                            StartDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            Address = "Zorgcentrum 4",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1972, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "irene.vd@example.com",
                            FirstName = "Irene",
                            LastName = "Van Dam",
                            StartDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            Address = "Gezondheidsstraat 2",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1980, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jeroen.f@example.com",
                            FirstName = "Jeroen",
                            LastName = "Faber",
                            StartDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Address = "Pijnbestrijding 1",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1997, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kim.s@example.com",
                            FirstName = "Kim",
                            LastName = "Schouten",
                            StartDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        },
                        new
                        {
                            Id = 13,
                            Address = "Welzijnshof 9",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1960, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lars.v@example.com",
                            FirstName = "Lars",
                            LastName = "Veenstra",
                            StartDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            Address = "Bewegingstraat 6",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1990, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mieke.b@example.com",
                            FirstName = "Mieke",
                            LastName = "Bos",
                            StartDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            Address = "Vitaliteitslaan 11",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1978, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "niels.d@example.com",
                            FirstName = "Niels",
                            LastName = "Dekker",
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            Address = "Herstelstraat 14",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1983, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olga.p@example.com",
                            FirstName = "Olga",
                            LastName = "Postma",
                            StartDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = 17,
                            Address = "Zorgpad 1",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1992, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paul.k@example.com",
                            FirstName = "Paul",
                            LastName = "Kuipers",
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            Address = "Medicijnlaan 3",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1975, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quinn.v@example.com",
                            FirstName = "Quinn",
                            LastName = "Vries",
                            StartDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            Address = "Oefenplein 5",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1987, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ruben.s@example.com",
                            FirstName = "Ruben",
                            LastName = "Smeets",
                            StartDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        },
                        new
                        {
                            Id = 20,
                            Address = "Genezingsweg 10",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1994, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.k@example.com",
                            FirstName = "Sarah",
                            LastName = "Koks",
                            StartDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            Address = "Sportlaan 2",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1968, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tim.v@example.com",
                            FirstName = "Tim",
                            LastName = "Visser",
                            StartDate = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = 22,
                            Address = "Kwaliteitsstraat 7",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1981, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ursula.b@example.com",
                            FirstName = "Ursula",
                            LastName = "Bouwman",
                            StartDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            Address = "Zorglaan 9",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1996, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vincent.m@example.com",
                            FirstName = "Vincent",
                            LastName = "Meijerink",
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            Address = "Therapieplein 12",
                            AssignedDoctorUserId = 4,
                            BirthDate = new DateTime(1979, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "wendy.vdv@example.com",
                            FirstName = "Wendy",
                            LastName = "van der Velde",
                            StartDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            Address = "Revalidatiepad 15",
                            AssignedDoctorUserId = 3,
                            BirthDate = new DateTime(1986, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "xavier.dr@example.com",
                            FirstName = "Xavier",
                            LastName = "De Ruiter",
                            StartDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        });
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.PatientNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PatientNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            Content = "Wondinfectie arm lijkt te verbeteren na start antibiotica.",
                            PatientId = 1,
                            Timestamp = new DateTime(2025, 1, 9, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 5,
                            Content = "Patiënt is gemotiveerd",
                            PatientId = 1,
                            Timestamp = new DateTime(2025, 1, 10, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganisatieId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Sophie",
                            LastName = "Jansen",
                            PasswordHash = "$2y$10$9mIxp6HbC1KobigZYb0qUu98xe11w45XH1kvPKX2qZ44BsF2qObDy",
                            Role = "Zorgverzekeraar",
                            Username = "zvm_jansen"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Mark",
                            LastName = "de Vries",
                            PasswordHash = "$2y$10$9mIxp6HbC1KobigZYb0qUu98xe11w45XH1kvPKX2qZ44BsF2qObDy",
                            Role = "Zorgverzekeraar",
                            Username = "zvm_devries"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Lisa",
                            LastName = "Bakker",
                            PasswordHash = "$2y$10$9mIxp6HbC1KobigZYb0qUu98xe11w45XH1kvPKX2qZ44BsF2qObDy",
                            Role = "Huisarts",
                            Username = "ha_bakker"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Thomas",
                            LastName = "Janssen",
                            PasswordHash = "$2y$10$9mIxp6HbC1KobigZYb0qUu98xe11w45XH1kvPKX2qZ44BsF2qObDy",
                            Role = "Huisarts",
                            Username = "ha_janssen"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Emma",
                            LastName = "Smit",
                            PasswordHash = "$2y$10$9mIxp6HbC1KobigZYb0qUu98xe11w45XH1kvPKX2qZ44BsF2qObDy",
                            Role = "Revalidatiearts",
                            Username = "ra_smit"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "David",
                            LastName = "Groen",
                            PasswordHash = "$2y$10$9mIxp6HbC1KobigZYb0qUu98xe11w45XH1kvPKX2qZ44BsF2qObDy",
                            Role = "Revalidatiearts",
                            Username = "ra_groen"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Linda",
                            LastName = "Visser",
                            PasswordHash = "$2y$10$9mIxp6HbC1KobigZYb0qUu98xe11w45XH1kvPKX2qZ44BsF2qObDy",
                            Role = "Revalidatiearts",
                            Username = "ra_visser"
                        });
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.AccessoryAdvice", b =>
                {
                    b.HasOne("RevaliInstruct.Core.Entities.Patient", null)
                        .WithMany("AccessoryAdvices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.ActivityLogEntry", b =>
                {
                    b.HasOne("RevaliInstruct.Core.Entities.Patient", null)
                        .WithMany("ActivityLogs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.Appointment", b =>
                {
                    b.HasOne("RevaliInstruct.Core.Entities.Patient", null)
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.ExerciseAssignment", b =>
                {
                    b.HasOne("RevaliInstruct.Core.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RevaliInstruct.Core.Entities.Patient", null)
                        .WithMany("Exercises")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.IntakeRecord", b =>
                {
                    b.HasOne("RevaliInstruct.Core.Entities.Patient", "Patient")
                        .WithOne("Intake")
                        .HasForeignKey("RevaliInstruct.Core.Entities.IntakeRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.InvoiceItem", b =>
                {
                    b.HasOne("RevaliInstruct.Core.Entities.Patient", null)
                        .WithMany("InvoiceItems")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.PainEntry", b =>
                {
                    b.HasOne("RevaliInstruct.Core.Entities.Patient", null)
                        .WithMany("PainEntries")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.Patient", b =>
                {
                    b.HasOne("RevaliInstruct.Core.Entities.User", "AssignedDoctor")
                        .WithMany("Patients")
                        .HasForeignKey("AssignedDoctorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedDoctor");
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.Patient", b =>
                {
                    b.Navigation("AccessoryAdvices");

                    b.Navigation("ActivityLogs");

                    b.Navigation("Appointments");

                    b.Navigation("Exercises");

                    b.Navigation("Intake");

                    b.Navigation("InvoiceItems");

                    b.Navigation("PainEntries");
                });

            modelBuilder.Entity("RevaliInstruct.Core.Entities.User", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
